/*
auto-generated by: https://github.com/react-spring/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useLoader } from 'react-three-fiber'
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useLoader(GLTFLoader, '/arch_logo.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        material={materials['Material.001']}
        geometry={nodes.Plane.geometry}
        position={[0, 0.19, 0.02]}
        rotation={[0, 0, -Math.PI / 2]}
      />
    </group>
  )
}
